### ISSUE TITLE
关于多页面打包的疑问

### ISSUE THREAD

**Issue by BelinChung** [fex-team/fis-packager-depscombine#2]
现在我有2个页面，使用 depscombine 配置了打包规则，其中：
`A.html` 依赖了 `a.js , b.js , c.js , d.js`
`B.html` 依赖了 `a.js , b.js , e.js , f.js`

按我的预期，打包后是这样的
`A.html` 使用了 `a-b-c-d.js` 这个包
`B.html` 使用了 `a-b-e-f.js` 这个包

而实际上却是：
`A.html` 使用了 `a-b-c-d.js` 这个包
`B.html` 使用了 `a-b-c-d.js` 、 `e-f.js` 这两个包

我觉得这样不是太好吧？按照我预期那种，打包后只会包代码有冗余，而现在的情况是页面之间的包出现了交叉了。

**Comment by oxUnd** [comment]
@BelinChung 你是 to-page 的打包方式，这个你搞一个插件弄一下；

**Comment by 2betop** [comment]
这个问题，被讨论了 N 次了，交叉不代表不好啊。

快看看这个：https://github.com/fex-team/fis/issues/488#issuecomment-101989042

**Comment by BelinChung** [comment]
@2betop 我是昨天在群里看了这个讨论才有这个疑问的
然后结合我现在的需求：
我的 login.html 页面引用了 main.html 那么大的包，显然有点不合适
意思这个插件原本就是设计为交叉打包这种形式的了？

PS：目前我是手动把交叉部分独立打成一个包，也是OK的

**Comment by 2betop** [comment]
如果用后端来做 pkg 包选择，那没办法，只能做到一个资源只能打包到一个个包，所以没法满足 a-b 同时在两个包里面的需求。

但是呢：纯前端是可以做的，就是编译时分析页面，a - b -c -d 合成一个新文件， a -b -e -f 合成一个新文件，然后对应的在页面的 引用处换成新文件。

**Comment by 2betop** [comment]
[simple](https://github.com/hefangshi/fis-postpackager-simple) 里面用的方式2，但是仅限于纯前端项目。看你的项目类型吧。

**Comment by BelinChung** [comment]
OK，我收集多几种打包方案，这块还是有很多可以探讨的
