### ISSUE TITLE
这个插件支持fis3吗

### ISSUE THREAD

**Issue by xjchenhao** [fex-team/fis-packager-depscombine#3]
我的`fis-conf.js`配置如下:

```
.match('::package', {
        packager: fis.plugin('depscombine')
    }, true);
```

也尝试过`fis2`的写法,在页面顶部写了:

```
fis.config.set('modules.packager', 'depscombine');
```

依赖都没有合并成功,不知道怎么写了,求解惑.

**Comment by 2betop** [comment]
fis3 你用这个 https://github.com/fex-team/fis3-packager-deps-pack

有更多功能。

**Comment by xjchenhao** [comment]
谢谢,用`fis3-packager-deps-pack`配置成功了.
